[package]
name = "gday"
version = "0.0.1"
edition = "2021"

[dependencies]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
unwrap_used = "deny"
pedantic = "deny"
missing_errors_doc = "allow"
must_use_candidate = "allow"
nursery = "deny"
module_name_repetitions = "allow"
