[package]
name = "gday"
version = "0.0.1"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
burn-import = { path = "../burn/crates/burn-import" }

[dependencies]
burn = { path = "../burn/crates/burn" }
burn-import = { path = "../burn/crates/burn-import" }
burn-ndarray = { path = "../burn/crates/burn-ndarray" }
clap = { version = "4.4.11", features = ["derive"] }
v4l = "0.14.0"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
unwrap_used = "deny"
pedantic = "deny"
missing_errors_doc = "allow"
must_use_candidate = "allow"
nursery = "deny"
module_name_repetitions = "allow"
