name: "Check and build"
on:
  pull_request:
  push:
jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: LFS pull
        run: git lfs pull
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check
      - run: nix develop --command cargo fmt -- --check
      - run: nix develop --command cargo clippy
      - run: nix build
