name: "CI"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip models
        run: ./scripts/unzip_models.sh
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check
      - run: nix develop --command cargo fmt -- --check
      - run: |
          nix develop --command bash -c "export RUSTFLAGS='-D warnings' && cargo clippy"
      - run: |
          nix develop --command bash -c "export RUSTFLAGS='-D warnings' && cargo test"
      - run: nix build
